### ISSUE TITLE
unsupported operand type.

### ISSUE THREAD

**Issue by ravikumarpundr** [GregoryMorse/trendln#1]
i am trying to use your code but getting follow error.

File "tend.py", line 9, in <module>
    minimaIdxs, maximaIdxs, pmin, pmax, mintrend, maxtrend, minwindows, maxwindows =calc_support_resistance(hist,extmethod = METHOD_NUMDIFF,method=METHOD_NSQUREDLOGN,window=125,errpct = 0.005,hough_scale=0.01,hough_prob_iter=10,sortError=False)

line 384, in calc_support_resistance
    scale = (max_h - min_h) / len_h
TypeError: unsupported operand type(s) for -: 'str' and 'str'

**Comment by GregoryMorse** [comment]
Can you tell me what your history variable contains e.g. print(hist) - as the error indicates you are passing string data but the data must be in numeric format.  float(hist) might resolve this.

**Comment by 5xcor** [comment]
This is a problem with input data. In the example:
change from:
minimaIdxs, maximaIdxs, pmin, pmax, mintrend, maxtrend, minwindows, maxwindows =  calc_support_resistance(
	# list of data as float
	hist,

on this:
minimaIdxs, maximaIdxs, pmin, pmax, mintrend, maxtrend, minwindows, maxwindows =   calc_support_resistance(
	# list of data as float
	hist[-1000:].Close,

**Comment by GregoryMorse** [comment]
I will fix that.  As well I should add checks to make sure input data is valid.  It should never crash in the code.  It should always give a friendly error when bad input values are passed.  Given that I am trying to make it hold to the standards of a library.  Perhaps that is why it was reported.  I would appreciate any more reports where it crashes in the code as by definition it should only raise errors by parameter checking.

In the upcoming object oriented restructuring, a lot will change given that it can be used on any type of numeric data, even using Highs for maxima and Lows for minima, etc.  Or doing just support only or resistance trends for example.

**Comment by GregoryMorse** [comment]
Please see again usage example in readme as it is correct and per comments here.  The parameter validation will catch this in 0.1.10.
