### ISSUE TITLE
METHOD

### ISSUE THREAD

**Issue by 5xcor** [GregoryMorse/trendln#4]
I trying the method, and METHOD_NAIVE and METHOD_NAIVECONSEC is look like identicals.

If you want to see, I send the jupyter file in my fork.

Milan

**Comment by GregoryMorse** [comment]
Well the only real difference is that NAIVECONSEC will find maximum or minimum with consecutive values.  e.g. 1, 2, 2, 2, 1 is only found with NAIVECONSEC and not found with NAIVE as its truly quite naïve :).  Make sure your data has maxima or minima that are repeated multiple times.

I really appreciate your reports and anything you notice feel free to raise as an issue.  Next release will resolve as many things as I can to stabilize the edge cases in the library.

**Comment by GregoryMorse** [comment]
This is an observation, but not an issue since the 2 methods often can return identical values.
